### ISSUE TITLE
Could not resolve all files for configuration ':app:_internal_aapt2_binary'

### ISSUE THREAD

**Issue by haruelrovix** [VISI-ONE/create-react-native-web-app#10]
**Describe the bug**
`yarn android` throws an error on Android Studio with **gradle:3.2.1**

**To Reproduce**
1. Initialize CRNWA project
2. Run `yarn android`
3. Error

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:_internal_aapt2_binary'.
> Could not find com.android.tools.build:aapt2:3.2.1-4818971.
```

**To Fix**
This project uses gradle [2.2.3](https://github.com/VISI-ONE/create-react-native-web-app/blob/215ea61b57adc7b5f8f5c8da8f43fa2474ee1d58/template/android/build.gradle#L8)
```java
    classpath 'com.android.tools.build:gradle:2.2.3'
```

Simply add google repository and it should be fine.
```java
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

```

**Profit**
<img src="https://user-images.githubusercontent.com/17120764/48238437-9ae91e00-e3fd-11e8-8e6b-248ed8c290b3.jpeg" width=300 />

Hope it helps someone out there trying to get started with CRNWA. 🤝

**Comment by orYoffe** [comment]
solved with PR #8

**Comment by tarccio** [comment]
Google() is already added. What to do next ?

**Comment by eliasdominguezpires** [comment]
https://www.codegrepper.com/code-examples/whatever/Could+not+resolve+all+files+for+configuration+%27%3Aapp%3A_internal_aapt2_binary%27.
add in 
allprojects {
    repositories {
    .... 
    ....
    maven {
        url "https://maven.google.com"
    }
