### ISSUE TITLE
Snapshot separation

### ISSUE THREAD

**Issue by orYoffe** [VISI-ONE/create-react-native-web-app#12]
**Is your feature request related to a problem? Please describe.**
currently the snapshots are being placed in the usual __snapshots__ dedicated folder.

**Describe the solution you'd like**
Jest just introduced a snapshot folder resolver to enable using different folders thus enabling us to create one for native and one for web in each component 

**Additional context**
if you do snapshots for both platforms one will delete the other as it would mark it as obsolete

**Comment by geminiyellow** [comment]
in v1, i use `coverageDirectory` something like

```
coverageDirectory: 'coverageNative',
```

for coverage result, and use `__[Platform]_snapshoot__` in `switchSnapshots` for jest snapshot result.

**Comment by orYoffe** [comment]
hi @geminiyellow,
this feature is planned for the future, since jest offers to choose a directory for your snapshots.
you can copy the jest config, switchSnapshots.js file and the npm scripts commands from v1 in order to fix your project for now.. but this feature will change this to two folders I think

**Comment by orYoffe** [comment]
will be available with jest v24
https://github.com/facebook/jest/issues/1650#issuecomment-435545153

**Comment by orYoffe** [comment]
after testing the new feature i found jest 24 has issues with react-native v55 and since react-native-web only supports v55 not much can be done at this point
