### ISSUE TITLE
v2 test cause red warning

### ISSUE THREAD

**Issue by geminiyellow** [VISI-ONE/create-react-native-web-app#16]
use v2 create a new project then `npm run test`

```
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
```
**Screenshots**

![image](https://user-images.githubusercontent.com/929878/49350114-0bc7e100-f6f1-11e8-939f-5656729511d9.png)

**Comment by orYoffe** [comment]
@geminiyellow I plan to add more functionality for testing in the future
For now, you can easily solve this error by adding this code before your tests run
```
if (typeof window !== 'undefined') {
    if (typeof HTMLCanvasElement !== 'undefined') {
    // taken from https://stackoverflow.com/questions/48828759/jest-and-jsdom-error-with-canvas
      HTMLCanvasElement.prototype.getContext = () => {
        // return whatever getContext has to return
      };
    }
}
```

you can add another script to jest here in the package.json file:
```
"setupFiles": [
      "react-app-polyfill/jsdom",
     "path/to/new/script"
 ],
```

**Comment by geminiyellow** [comment]
ok thank you @orYoffe
