### ISSUE TITLE
How to include babel plugins?

### ISSUE THREAD

**Issue by jamespacileo** [VISI-ONE/create-react-native-web-app#25]
Hi,

I'm trying to install **class property support** to imported libraries (via **@babel/plugin-proposal-class-properties**), react-native-vector-icons break for example.

This is the error I get:

    Failed to compile.

    ./node_modules/react-native-vector-icons/lib/create-icon-set-from-fontawesome5.js
    SyntaxError: .....\create-icon-set-from-fontawesome5.js: Support for the experimental syntax 'classProperties' isn't currently enabled (134:24):

    132 |   function createFA5iconClass(baseClass, selectClass = iconSet => iconSet) {
    133 |     class FA5iconClass extends PureComponent {
    > 134 |       static propTypes = {
        |                        ^
    135 |         light: PropTypes.bool,
    136 |         solid: PropTypes.bool,
    137 |       };

    Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.

Tried adding @babel/plugin-proposal-class-properties in `webpack.config.dev.js` on line 224 to no avail, see below

    plugins: [
        [
            require.resolve("@babel/plugin-proposal-class-properties")
        ],
        [
            require.resolve('babel-plugin-named-asset-import'),
            {
            loaderMap: {
                svg: {
                ReactComponent: '@svgr/webpack?-prettier,-svgo![path]',
                },
            },
            },
        ],
    ],

any idea on how I can include support for additional es features, I'm stuck. Thanks :)

**Comment by BenjaminHabert** [comment]
Hello @jamespacileo ; I ran into the same issue a few days ago but was not able to solve it. Can you provide more details on the changes you made that allowed you to support react-native-vector-icons ?

**Comment by orYoffe** [comment]
Hi @jamespacileo 
the problem might be compiling this code from es6 to es5. So you should add them in your webpack config like in this issue https://github.com/VISI-ONE/create-react-native-web-example/issues/1#issuecomment-401526167

Hope it helps :)

**Comment by iksent** [comment]
@jamespacileo, please help us with connecting [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons). We really need more info. Wanna focus on RN code, without spending hours on setting up project settings just to make it work.

1. Should we add [@expo/vector-icons](https://github.com/expo/vector-icons) or we just should use only react-native-vector-icons? For example, I want to use it both for mobile devices and web.
When I am not installing @expo/vector-icons package, I get this error: 
```./src/App.js
Module not found: Can't resolve '@expo/vector-icons/FontAwesome' in 'C:\Android\dev\ReactNativeWebGenerator\src'```
But after installing @expo/vector-icons package I get same error as @jamespacileo gets:
```Support for the experimental syntax 'classProperties' isn't currently enabled```

2. I tried these settings (in config/webpack.config.dev.js), but it didn't help me:
```
...
          // Process application JS with Babel.
          // The preset includes JSX, Flow, and some ESnext features.
          {
            test: /\.(js|mjs|jsx|ts|tsx)$/,
            include: [
                paths.appSrc,
                path.resolve('../node_modules/react-native-vector-icons/'),
            ],
            loader: require.resolve('babel-loader'),
...
```

**Comment by orYoffe** [comment]
@iksent I use the same library but their docs say just to add ttf loader to webpack configs 
https://github.com/oblador/react-native-vector-icons#web-with-webpack
```
      {
        test: /\.ttf$/,
        loader: "url-loader", // or directly file-loader
        include: path.resolve(__dirname, "node_modules/react-native-vector-icons"),
      },
```
it worked for me just to follow their instructions.

you might want to remove `babel-preset-expo` from your babel config.. in v0.1.10 i removed expo all together.
please check it out: https://github.com/VISI-ONE/create-react-native-web-app/blob/master/template/babel.config.js#L4
