### ISSUE TITLE
Unable to use React Navigation

### ISSUE THREAD

**Issue by Selvamhibiz** [VISI-ONE/create-react-native-web-app#3]
![error](https://user-images.githubusercontent.com/19421975/43453183-0b76feba-94d7-11e8-8f4d-ba4eba5e96ff.png)
I created a web app using create-react-native-web-app. I need to navigate to login and registration screens from initial screen. I have installed react-navigation npm and imported stack navigator in my project. It fails to compile stating that 'You may need an appropriate loader to handle this file type.' Caught up with this error for the whole day. I have updated my webpack.config file, plugins, etc. Need help on fixing this issue.

**Comment by orYoffe** [comment]
Hi @Selvamhibiz 
the problem is compiling this code from es6 to es5. So you should add them in your webpack config like in this issue https://github.com/VISI-ONE/create-react-native-web-example/issues/1

Hope it helps :)
