### ISSUE TITLE
“Unhandled JS Exception: Can't find variable setTimeout” in iOS only

### ISSUE THREAD

**Issue by robbiemu** [VISI-ONE/create-react-native-web-app#31]
**Describe the bug**
first of all, the part that seems to work out of the box is the web part. In my first attempt, after running `npx create-react-native-web-app demo-app`, `yarn web` immediately worked. :)

When running `yarn iOS` once I get successful builds, I get the error _“Unhandled JS Exception: Can't find variable setTimeout”_.

**To Reproduce**
I have `node -v >> v11.5.0`. I'm on Mohave, with xcode 10.1 already setup (for iOS development).

*    I needed to install the xcode 10.1 commandline tools though.
*    Then, I needed to `yarn iOS`
*    followed by opening the creaternwapp project under `ios/` and change the `Project Settings` > `Build System` to _Legacy Build System_.
*    Then I had to attempt to build it in xcode. (turns out this is important, even though build will fail)
*    Then, `(cd node_modules/react-native/third-party/glog-0.3.4/ && ./configure)` `// those numbers may change apparently, depending on install`

*    whether I needed to or not, I changed the .babelrc from:
```json
{
    "presets": ["module:metro-react-native-babel-preset"],
}
```
to:
```json
{
  "presets": [["module:metro-react-native-babel-preset"], ["react-app"]],
  "ignore": ["node_modules/art/core/color.js"],
  "plugins": [
    ["module-resolver", {
      "alias": {
        "^react-native$": "react-native-web"
      }
    }]
  ],
}
```
*    then: `npm install && npm audit fix` and followed that with `yarn install` so yarn could get control back.

At this point `yarn ios` succeeds, but the error with setTimeout is showing on the simulator. I researched that, and apparently these sorts of errors happen when react-native install isn't complete, with the suggested solution to yarn upgrade react native. But `yarn upgrade react-native@0.57.8` doesn't change anything for me.

**Expected behavior**
Along with `yarn web` working just like it does, `yarn iOS` should also work without error

**Screenshots**
![screenshot](https://i.imgur.com/KEvVfye.png)

**Desktop (please complete the following information):**
 - OS: Mohave
 - Browser Simulator
 - Version 10.1

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: 12.1
 - Browser Simulator
 - Version 10.1

**Additional context**
https://stackoverflow.com/questions/54328936/unhandled-js-exception-cant-find-variable-settimeout-in-ios-only

**Comment by orYoffe** [comment]
Hi @robbiemu 
react-native-web only supports react-native v0.55 currently
about Xcode, did you see this link https://github.com/facebook/react-native/issues/19573
from the readme https://github.com/VISI-ONE/create-react-native-web-app#troubleshooting
might help

**Comment by robbiemu** [comment]
I solved my problem by switching to expo
