### ISSUE TITLE
export 'default' (reexported as 'normalize') was not found in './helpers/normalizeText'

### ISSUE THREAD

**Issue by thorakmedichi** [VISI-ONE/create-react-native-web-app#33]
**Describe the bug**
When running `yarn web` I am now getting this error

```
Support for the experimental syntax 'classProperties' isn't currently enabled (41:23):

  39 |
  40 | export default class SwipeRating extends Component {
> 41 |   static defaultProps = {
     |                       ^
  42 |     type: 'star',
  43 |     ratingImage: require('./images/star.png'),
  44 |     ratingColor: '#f1c40f',

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.

```

**To Reproduce**
`yarn web`

**Expected behavior**
The web version to run

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3
 - Browser Chrome  72.0.3626.96 and Firefox 65.0

**Smartphone (please complete the following information):**
`yarn android` works fine

**Additional context**
I modified babel.config.js based on StackOverflow comments but it didnt seem to work
```
module.exports = function (api) {
    api.cache(true);
    return {
        presets: [['module:metro-react-native-babel-preset'], ['react-app']],
        ignore: ['node_modules/art/core/color.js'],
        plugins: [
            ['module-resolver', {
                'alias': {
                    '^react-native$': 'react-native-web'
                }
            }],
            ['@babel/plugin-proposal-class-properties', {
                'loose': true
            }]
        ],
    };
};
```

**Comment by thorakmedichi** [comment]
After some mucking about I think I solved the above error but now I get this
```
./node_modules/react-native-elements/src/index.js
"export 'default' (reexported as 'normalize') was not found in './helpers/normalizeText'
```

**Comment by jschmidtnj** [comment]
I'm having the same problem...

**Comment by arthurpankiewicz** [comment]
I followed the same instructions and I am running into the same problem as thorakmedichi

**Comment by orYoffe** [comment]
this issue is related to react-native-elements not to this repo. please open an issue here https://github.com/react-native-training/react-native-elements

IMO it seems like a problem with es6 library that you need to add to webpack js paths so it compiles them with babel too

**Comment by obiwankenoobi** [comment]
@thorakmedichi Hey, any luck with this?

**Comment by orYoffe** [comment]
@obiwankenoobi and @thorakmedichi @jschmidtnj @arthurpankiewicz 
I would suggest to look over this issue.. might help
https://github.com/orYoffe/create-react-native-web-app/issues/44
