### ISSUE TITLE
upgrade to webpack 4 and babel 7

### ISSUE THREAD

**Issue by geminiyellow** [VISI-ONE/create-react-native-web-app#4]
hi @orYoffe , do you want to upgrade the webpack to 4 and the babel to 7?

**Comment by orYoffe** [comment]
Hi @geminiyellow, thanks for the suggestion. I would be happy to but I would wait for create-react-app to upgrade to babel 7 and webpack 4 and then i will recreate it from that project.
PRs are welcome :)
