### ISSUE TITLE
Cant create app using create-react-native-web-app

### ISSUE THREAD

**Issue by vidalbenjoe** [VISI-ONE/create-react-native-web-app#5]
Hello, I can't create app using create-react-native-web-app, it displays an error -bash: create-react-native-web-app: command not found but I already installed it using npm install -g create-react-native-web-app

**Comment by vidalbenjoe** [comment]
Hi, no need for the answer, I solved it already, here's the solution:

mkdir ~/.npm-global
Configure npm to use the new directory path:
npm config set prefix '~/.npm-global'
Open or create a ~/.profile file and add this line:
export PATH=~/.npm-global/bin:$PATH
Back on the command line, update your system variables:
source ~/.profile

**Comment by orYoffe** [comment]
Thanks for being active and solving it yourself.. this helps the community :)
